// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqmmgecqjecwuumpvpjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbW1nZWNxamVjd3V1bXB2cGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNTM0MzIsImV4cCI6MjA2MTYyOTQzMn0.vnVX_ob9LYtdRpWie9tvQDnY5jl5BqE9y0UUdSN6owc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);